### ISSUE TITLE
Feat: Add a Favicon for the Website

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [dakshsinghrathore/Brighter-Beginnings#55] opened 2024-01-04 17:17 UTC
### Describe the feature

Currently the website don't have any Favicon. We should add the favicon for the Website.

### Add ScreenShots

![brighter begg](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/133518394/bc3561ff-76cc-4d70-b77c-24ca0265c4b2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Shreyas-SAS** [comment] 2024-01-04 18:04
This is a duplicate of issue #17 and #20 that is already solved with PR #41

**Closed** 2024-01-05 05:08 UTC
