### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by Manishkr1007** [dakshsinghrathore/Brighter-Beginnings#60] opened 2024-01-05 06:35 UTC
### Describe the feature

Make about page user intractive .

### Add ScreenShots

![Screenshot (105)](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/113241137/f520f27c-1173-4a2e-aca4-da8b82d4f43b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Shreyas-SAS** [comment] 2024-01-05 10:45
duplicate of closed issue #11

**Comment by Manishkr1007** [comment] 2024-01-05 15:59
> duplicate of closed issue #11

hey in issue #11 has not mention that he want to add the new page or new feature on this project 
he just find a issue and want contribute as developer of this about page.

**Comment by Shreyas-SAS** [comment] 2024-01-05 17:28
> > duplicate of closed issue #11
> 
> hey in issue #11 has not mention that he want to add the new page or new feature on this project 
> he just find a issue and want contribute as developer of this about page.
> 

Well I guess developing the about page means creating it given that there is no about page. But still if @dakshsinghrathore is ok with it then I guess it's good to go. 

I was anyways finding issues with the 3rd box unchecked which means it's open for me to contribute. 😂

It's good if you could take it up.

**Closed** 2024-02-12 15:12 UTC
Labels: documentation, SWOC S4
